#steGutDecoder
 
newString = input("What would you like to decode?\n")
 
temp = newString.replace("", "")
temp = temp.replace(".", "")
temp = temp.replace(",", "")
temp = temp.replace("secretword", "")
temp = temp.lower()
newString = temp
 
MobyDictionaryDecoder = {
' ': '',
'alter': ' ',
'of':        '!',
'and':     '"',
'in':         '#',
'to':        '$',
'ant':      '%',
'that':    '&',
'cow': '\'',
'it':          '(',
'but':      ')',
'by':        '*',
'as':        '+',
'at':         ',',
'his':       '-',
'with':    '.',
'whale': '/',
'for':       '0',
'all':        '1',
'their': '2',
'from':   '3',
'this':     '4',
'are':      '5',
'was':     '6',
'they':   '7',
'so':        '8',
'one':     '9',
'be':       ',',
's':           ';',
'he':       '<',
'fish':     '=',
'on':       '>',
'which': '?',
'had':     '@',
'or':        'A',
'what':  'B',
'whales': 'C',
'not':      'D',
'when': 'E',
'these': 'F',
'now':    'G',
'like':      'H',
'have':   'I',
'then':   'J',
'some': 'K',
'were':  'L',
'i':            'M',
'tail':       'N',
'them':  'O',
'we':      'P',
'upon':  'Q',
'other': 'R',
'more':  'S',
'you':     'T',
'if':          'U',
'him':     'V',
'into':     'W',
'fast':     'X',
'an':        'Y',
'up':       'Z',
'time':   '[',
'been':  '\\',
'those': ']',
'seemed':'^',
'there': '_',
'still': '`',
'our':      'a',
'no':       'b',
'her':      'c',
'us':        'd',
'the':      'e',
'line':     'f',
'two':     'g',
'though': 'h',
'only':    'i',
'any':     'j',
'boat':   'k',
'would': 'l',
'will':      'm',
'most':  'n',
'after': 'o',
'has':      'p',
'its':        'q',
'last':      'r',
'long':    's',
'away':  't',
'such':   'u',
'sperm': 'v',
'flukes': 'w',
'very':    'x',
'might': 'y',
'great': 'z',
'may':    '{',
'yet':      '|',
'between': '}',
'lord':     '~',
'tab': '\t',
'whatever': '\n',
'moby': '`',
'': ''
}
 
newerString = ""
for word in newString.split(" "):
 
    newerString = newerString + str(MobyDictionaryDecoder[word])
 
print("\nFinal:\n_____________________\n")
print(newerString)
